# Generated by Django 3.0.7 on 2020-06-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='LastName')),
            ],
        ),
    ]
